name: reminder
description: A new Flutter package project.
version: 0.0.1

publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  lib_dependencies:
    path: ../../packages/lib_dependencies
  lib_core:
    path: ../../packages/lib_core
  lib_reminder:
    path: ../../packages/lib_reminder

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: