include: package:flutter_lints/flutter.yaml

linter:
  rules:
    public_member_api_docs: false
    type_annotate_public_apis: false
    omit_local_variable_types: false
    use_key_in_widget_constructors: false
    avoid_types_on_closure_parameters: false
    lowercase_with_underscores: false
    avoid_positional_boolean_parameters: false
    sort_constructors_firsts: false
    one_member_abstracts: false
    constant_identifier_names: false
    lines_longer_than_80_chars: false
    curly_braces_in_flow_control_structures: false
    avoid_catches_without_on_clauses: false
    comment_references: false
    always_put_control_body_on_new_line: false
    prefer_single_quotes: true
    always_put_required_named_parameters_first: false
    use_setters_to_change_properties: false
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_double_and_int_checks: true
    avoid_empty_else: true
    avoid_field_initializers_in_const_classes: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_relative_lib_imports: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    avoid_unused_constructor_parameters: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: true
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    hash_and_equals: true
    implementation_imports: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    join_return_with_assignment: true
    library_names: true
    library_prefixes: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_duplicate_case_values: true
    file_names: true
    null_closures: true
    package_api_docs: true
    package_names: true
    package_prefixed_library_names: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: false
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_generic_function_type_aliases: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_typing_uninitialized_variables: true
    recursive_getters: true
    slash_for_doc_comments: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_rethrow_when_possible: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
    valid_regexps: true
    void_checks: true
    sort_pub_dependencies: false
    overridden_fields: false
