name: lib_dependencies
description: A new Flutter package project.
version: 0.0.1

publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons & Widgets
  cupertino_icons: ^1.0.5
  flutter_staggered_grid_view: ^0.6.2

  # Local Storage
  sembast: ^3.4.4

  # Utils
  equatable: ^2.0.5
  dartz: ^0.10.1
  path_provider: ^2.0.14
  file: ^6.1.4

  # Injection & Navigation
  flutter_modular: ^5.0.3

  # State Manager
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
