name: lib_dependencies
description: A new Flutter package project.
version: 0.0.1

publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons & Widgets
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.6.1

  # Local Storage
  sembast: ^3.2.0

  # Utils
  equatable: ^2.0.3
  dartz: ^0.10.1
  path_provider: ^2.0.9

  # Injection & Navigation
  flutter_modular: ^4.5.0

  # State Manager
  flutter_bloc: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
